version: '3'

services:
  
  redis:
    image: redis:latest  
    ports:
     - "6379:6379"
    volumes:
     - /data/redis:/data   
    networks:
     - network      
     
  db:
    image: mysql:5.7
    ports:
     - "3307:3307"
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=caju
     - MYSQL_USER=root
     - MYSQL_ROOT_PASSWORD=ro07
    networks:
     - network 

networks:
  network:
    driver: bridge